### ISSUE TITLE
LP2 Running Android

### ISSUE THREAD

**Issue by F1LT3R** [nirajsanghvi/CLLP#8]
Hi Niraj, cool project!

I'd like to get this running at some point.

I see you're using Gradle. Is LP2 running Android?

If so, do you know which version?

**Comment by nirajsanghvi** [comment]
Thanks for the comment! I think there may be some confusion here. CLLP is an Android app (not officially affiliated with Light, the company) that runs on an Android smartphone as described in this repository's readme to provide tools to users of the Light Phone 2 that also have an Android device. The CLLP app is built using the Android SDK (Gradle is the default build system used for Android apps built using Android Studio).

The LP2 device itself runs AOSP and uses React Native as a pseudo-OS, and the technical details of it are described in their blog post here:
https://medium.com/sanctuary-computer-inc/building-lightos-with-react-native-4b6e4ad1cd7f

To be clear, the CLLP app does not run anything on the Light Phone itself. Since there is not an SDK for the Light Phone available yet, CLLP requires you to send commands from your Light Phone 2 over SMS. I consider it a useful hack until an actual SDK is available that would allow for more native tools, rather than having to use SMS as a communication channel as I am doing currently.

If you're looking to get started using CLLP and have read through [the readme](https://github.com/nirajsanghvi/CLLP/blob/master/README.md), there's a nice walkthrough to getting setup that a Reddit user put on YouTube:
https://www.youtube.com/watch?v=cvBvkHgLXnA

If you have any other trouble, feel free to contact me at vanishingjar [at] gmail.com. For now, I'm closing this issue since this is primarily for bug reporting.
