### ISSUE TITLE
Support open source maps

### ISSUE THREAD

**Issue by samtay** [nirajsanghvi/CLLP#9]
I saw in your README that users are required to set up their own API key because of google's pricing structure. Have you considered using something open source instead, such as [grasshopper](https://github.com/graphhopper/graphhopper/) which uses OpenStreetMap? Since it's just directions, I imagine it would behave almost identically. I think most LP2 users are also trying to move away from Google services, so it might better fit the users of your app.

**Comment by nirajsanghvi** [comment]
@samtay Great point! At the time I was just going with the solution I preferred since really it was just supposed to be a temporary stopgap until directions were implemented by the Light team natively. Revisiting it now, though their timeline has shifted it does sound like directions are still the next major feature for release on their roadmap, currently targeting the start of 2021.

I'll still do some investigating to see how much effort it would be to add OSM or something similar though, thanks for the suggestion.

**Comment by nirajsanghvi** [comment]
Closing this issue since I think the native directions app released for the Light Phone accomplished this.
